export const ENEMIES = {
  FODDER_BASIC: {
    id: 'FODDER_BASIC',
    name: 'Drone',
    hp: 20,
    speed: 50,
    damage: 5,
    radius: 0.5,
    xpReward: 10,
    behavior: 'chase',
    spawnWeight: 100,
    modelKey: 'drone',
    modelPath: '/models/enemies/Robot%20Enemy%20Flying.glb',
    color: '#ff5555',
    meshScale: [3, 3, 3],
  },
  FODDER_FAST: {
    id: 'FODDER_FAST',
    name: 'Scout',
    hp: 12,
    speed: 90,
    damage: 3,
    radius: 0.4,
    xpReward: 8,
    behavior: 'chase',
    spawnWeight: 60,
    modelKey: 'scout',
    modelPath: '/models/enemies/Robot%20Enemy%20Flying%20Gun.glb',
    color: '#ff3366',
    meshScale: [2.5, 2.5, 2.5],
  },
}
