import { GAME_CONFIG } from '../config/gameConfig.js'

export const ENEMIES = {
  // Type 1: Basic Chaser
  FODDER_BASIC: {
    id: 'FODDER_BASIC',
    name: 'Drone',
    type: 1,
    hp: 20,
    speed: 17,
    damage: 5,
    radius: 1.5,
    xpReward: 12,
    behavior: 'chase',
    spawnWeight: 100,
    modelPath: '/models/enemies/robot-enemy-flying.glb',
    meshScale: [3, 3, 3],
    color: null,
  },

  // Type 2: Tank Chaser
  FODDER_TANK: {
    id: 'FODDER_TANK',
    name: 'Tank Drone',
    type: 2,
    hp: 40,
    speed: 12,
    damage: 5,
    radius: 2.0,
    xpReward: 15,
    behavior: 'chase',
    spawnWeight: 60,
    modelPath: '/models/enemies/robot-enemy-flying.glb',
    meshScale: [4, 4, 4],
    color: null,
  },

  // Type 3: Swarm Fast Sweep
  FODDER_SWARM: {
    id: 'FODDER_SWARM',
    name: 'Swarm Scout',
    type: 3,
    hp: 8,
    speed: 35,
    damage: 3,
    radius: 0.75,
    xpReward: 5,
    behavior: 'sweep',
    spawnWeight: 40,
    modelPath: '/models/enemies/robot-enemy-flying.glb',
    meshScale: [1.5, 1.5, 1.5],
    color: null,
  },

  // Type 4: Shockwave Blob
  SHOCKWAVE_BLOB: {
    id: 'SHOCKWAVE_BLOB',
    name: 'Shockwave Blob',
    type: 4,
    hp: 15,
    speed: 8,
    damage: 5,
    radius: 2.5,
    xpReward: 20,
    behavior: 'shockwave',
    spawnWeight: 30,
    modelPath: '/models/enemies/enemy-blob.glb',
    meshScale: [2, 2, 2],
    color: null,
    shockwaveInterval: 3.5,
    shockwaveRadius: 15,
    shockwaveDamage: 8,
  },

  // Type 6: Sniper Mobile
  SNIPER_MOBILE: {
    id: 'SNIPER_MOBILE',
    name: 'Mobile Sniper',
    type: 6,
    hp: 25,
    speed: 20,
    damage: 0,
    radius: 1.5,
    xpReward: 25,
    behavior: 'sniper_mobile',
    spawnWeight: 25,
    modelPath: '/models/enemies/robot-enemy-flying-gun.glb',
    meshScale: [3, 3, 3],
    color: null,
    attackRange: 40,
    attackCooldown: 2,
    projectileSpeed: 80,
    projectileDamage: 10,
    projectileColor: '#ff3333',
  },

  // Type 7: Sniper Fixed
  SNIPER_FIXED: {
    id: 'SNIPER_FIXED',
    name: 'Fixed Turret',
    type: 7,
    hp: 10,
    speed: 0,
    damage: 0,
    radius: 1.5,
    xpReward: 30,
    behavior: 'sniper_fixed',
    spawnWeight: 10,
    modelPath: '/models/enemies/robot-enemy-flying-gun.glb',
    meshScale: [3, 3, 3],
    color: '#ff3333',
    attackRange: 60,
    attackCooldown: 4,
    telegraphDuration: 1.0,
    projectileSpeed: 150,
    projectileDamage: 20,
    projectileColor: '#ff0000',
  },

  // Type 8: Teleporter
  TELEPORTER: {
    id: 'TELEPORTER',
    name: 'Phase Shifter',
    type: 8,
    hp: 18,
    speed: 15,
    damage: 5,
    radius: 1.25,
    xpReward: 25,
    behavior: 'teleport',
    spawnWeight: 20,
    modelPath: '/models/enemies/robot-enemy-flying.glb',
    meshScale: [2.5, 2.5, 2.5],
    color: '#cc66ff',
    teleportCooldown: 5,
    teleportRange: 30,
    burstProjectileCount: 3,
    burstProjectileSpeed: 100,
    burstProjectileDamage: 5,
  },

  // Boss (separate system, not part of 8-type roster)
  // Values reference GAME_CONFIG to stay DRY with useBoss.jsx and GameLoop.jsx
  BOSS_SENTINEL: {
    id: 'BOSS_SENTINEL',
    name: 'Void Sentinel',
    type: 0,
    hp: GAME_CONFIG.BOSS_HP,
    speed: GAME_CONFIG.BOSS_MOVE_SPEED,
    damage: GAME_CONFIG.BOSS_CONTACT_DAMAGE,
    radius: GAME_CONFIG.BOSS_COLLISION_RADIUS,
    xpReward: 0,
    behavior: 'boss',
    spawnWeight: 0,
    modelPath: '/models/enemies/SpaceshipBoss.glb',
    color: '#cc66ff',
    meshScale: [8, 8, 8],
  },
}
