export const ENEMIES = {
  FODDER_BASIC: {
    id: 'FODDER_BASIC',
    name: 'Drone',
    hp: 20,
    speed: 17,
    damage: 5,
    radius: 1.5,
    xpReward: 10,
    behavior: 'chase',
    spawnWeight: 100,
    modelPath: '/models/enemies/robot-enemy-flying.glb',
    color: '#ff5555',
    meshScale: [3, 3, 3],
  },
  FODDER_FAST: {
    id: 'FODDER_FAST',
    name: 'Scout',
    hp: 12,
    speed: 30,
    damage: 3,
    radius: 1.2,
    xpReward: 8,
    behavior: 'chase',
    spawnWeight: 60,
    modelPath: '/models/enemies/robot-enemy-flying-gun.glb',
    color: '#ff3366',
    meshScale: [2.5, 2.5, 2.5],
  },
}
