// Planet definitions — scannable planets in the play area
export const PLANETS = {
  PLANET_CINDER: {
    id: 'PLANET_CINDER',
    name: 'Cinder Planet',
    tier: 'standard',
    scanTime: 5,
    color: '#a07855',
    emissiveColor: '#6b4c2a',
    emissiveIntensity: 0.2,
    scale: [8, 8, 8],
    modelKey: 'planetA',
    scanRadius: 40,
  },
  PLANET_PULSE: {
    id: 'PLANET_PULSE',
    name: 'Pulse Planet',
    tier: 'rare',
    scanTime: 10,
    color: '#00b4d8',
    emissiveColor: '#0096c7',
    emissiveIntensity: 0.6,
    scale: [12, 12, 12],
    modelKey: 'planetB',
    scanRadius: 50,
  },
  PLANET_VOID: {
    id: 'PLANET_VOID',
    name: 'Void Planet',
    tier: 'legendary',
    scanTime: 18,
    color: '#9b5de5',
    emissiveColor: '#7b45c5',
    emissiveIntensity: 1.0,
    scale: [16, 16, 16],
    modelKey: 'planetC',
    scanRadius: 60,
  },
}
